### PR TITLE
3 - Update with gapminder data

### PR DESCRIPTION
**Pull request by joelostblom**
This is the lecture that has gone through the most updates, essentially because it is the one that is the most dependent on finding interesting relationships in the data and must change when the data changes.

It is still very rough along the edges, but there is a line that i want to follow in terms of the analysis that are there. I think it is missing writing the narrative, cleaning up the analysis, improving transitions and potentially adding/removing something and replace it with something more interesting, but not that important.

### CODE REVIEW

**Comment by joelostblom** [comment]
@aays This is almost ready! I just need to update some in the last 5-10 cells which I will do tomorrow. If you want to have a quick look through and just say if it makes sense to you that would be great. Then we can go through in detail when you have more time on Monday.

**Comment by aays** [comment]
@joelostblom This looks great! Doesn't look like there's an awful lot of cleanup left either. Awesome work!

I'm not how to nicely format reviews of .ipynb files, so I'm just going to write some running comments below:

- Might be worth running `%matplotlib inline` at the very beginning regardless, since there's no downside to it - could also use this to explain inline plotting functionality of notebooks, and plus I think it's more time efficient than waiting for some of the class to potentially run into errors
- When introducing the `fig, ax` notation, is it worth defining what `fig` represents as well? (Up to you - just a thought!)
- This is minor, but I think the bit on pairplots as a first step in EDA should be its own section
- Although KDE is pretty cool and a big part of me would like to have it included, I feel like the full explanation a bit too advanced for this class. I don't think it's a bad idea to skip straight to the violin plot for that section
- Are you still planning on adding more challenges to the seaborn sections? I can help brainstorm if that's the case

That's really all I can think of for now. Otherwise, the structure is solid, and I'm not sure much needs to be changed there.

**Comment by joelostblom** [comment]
Great, thanks for the quick review @aays!

All great points you're raising:

1. The only downside is that it confuses students, at least last time there was uncertainty about what the percentage sign means, but that could just be explained better I guess... I also feel like the noteook is migrating away from having to use it at all since it is now enough to run a cell twice. But I also think its better to be explicit so I will switch it as you said.
2. Yes!
3. I will add a heading for this. I do like having it in the flow though so will not restructure I think.
4. Yes, I felt that when I was getting into it... Let's just say smoothened histogram for now and add this to my misc section of stuff that's not fitting in =) Maybe that can be a place for student to go as a next step after the workshop.
5. Yes! Let me upload the ones I am doing right now, maybe 1-2 hours, and then you can do the rest? Just so we don't end up doing the same ones. I will ping you!

I also changed the choice of columns I used for the end of the line plots section a bit just to fit with the challenges for that section. And it's more interesting now looking at CO2!

**Comment by aays** [comment]
@joelostblom Just a few more comments before I get to editing myself:

- In the 'Changing graph aesthetics' subsection of the seaborn content, the text says 'we will stick with the `white` style for the rest of this tutorial' but the following code cell has `sns.set(context='notebook', style='ticks', font_scale=1.4)`. Should that be changed to `white`?
- Underneath challenge 3 - what is the purpose of this cell?

```python
world_data = world_data.rename(columns={'co2_per_capita': 'co2_per_capita'})
```
- In the section before 'How to know which relationships to start exploring', the lesson abruptly switches from CO2 data to child mortality data - will those cells also be changed to work with CO2 data, or are we adding some sort of topic transition there? (I'm personally leaning towards sticking with just the CO2 data here, for the sake of time)
- Re: the correlations matrix - I'm not sure how much of it will be discussed in lecture 4, but I'm fine with including it here, even if very briefly
- I'm a little lost on what's going on after the box plots :(

**Comment by joelostblom** [comment]
@aays I will fix those things now!

- It should say `ticks` in the text also
- No purpose =)
- Yes, I'm going to make the second part into a challenge
- Not at all discussed in lecture 4, I might remove the scattermatrix and correlation part entirely to lec 4 since you already have a lot of material, what do you think? Or maybe leave them for now and in case you don't make it all the way lec4 will just start where you ended? That's proabbly better for now
- Yes I need to fix that.

**Comment by aays** [comment]
@joelostblom Awesome! I'm good with point 3 (turning the second part into the challenge), although I think keeping the very first corr matrix makes sense, just to motivate the next relationship that's looked at (income vs life expectancy) and thus better mimic an EDA workflow. If anything, we could keep the whole thing in there for now - I can gauge during the lesson itself how we're doing for time and whether to cover it or not in the moment. Up to you though, I'm good with either!

Though while we're on that topic of that section, it might be worth removing the pairplot that happens at the end of that section though - I think verbally mentioning that `hue` is a more 'global' parameter in seaborn functions might suffice. 

PS. I'm going to leave the lab now so I'll be offline for about an hour, but I'll be online and working on this for the rest of the night!

**Comment by joelostblom** [comment]
:+1: For your section it will be important to lead with a good data narrative. It was commented on today that it felt a bit like a functions and methods showcase rather than EDA. I'm trying to add some small comments to improve this, but also something just to keep in the back of your head when you talk about the data (we're still teaching them Python, so there needs to be a fair amount of showcasing of functionality).

**Comment by joelostblom** [comment]
@aays Essentially done, the last few cells need a bit of clean up but I have to run now. Fix it if you want or I can do it later tonight. Go ahead and do whatever you want with PR, merge if that is easier for you to work from and I can add to it later. Call or text me if something is unclear, I'll stay up until you're good.

**Comment by aays** [comment]
@joelostblom Great, thanks! I'll have a look-over, potentially make some minor edits, then merge the PR. Thanks for your awesome work on this!

**Comment by joelostblom** [comment]
@aays Suggestion: After you introduce yourself and the outline of what you will teach
today, could you do a short review as part of the setup? Just these
6-7 questions to the audience. Maddy did something similar last time and it seemed
to be very appreciated. They will need to remember this to follow along in your
lecture also.


Do you remember how to:

1. Read in the data from the csv file from yesterday?

```
import pandas as pd

world_data = pd.read_csv('https://raw.githubusercontent.com/UofTCoders/2018-09-10-utoronto/gh-pages/data/world-data-gapminder.csv')

# They should also have saved it locally yesterday.
# surveys = pd.read_csv("world_data.csv")
```

2. How to select only the columns 'country' and 'year' from the data frame?

```
world_data[['country', 'year']]
```

3. How to select a few rows together with the columns above?

```
world_data.loc[[1, 13, 24], ['country', 'year']]
```

4. How to select only data from year 1995?

```
world_data.loc[world_data['year'] == 1995]
```


5. Select only the rows where the region is Asia or Africa.

```
world_data.loc[world_data['region'].isin(['Asia', 'Africa'])]

```

6. Calculate the total population in each region

```
world_data.groupby('region')['population'].sum()
```

(7.) Get the number of countries in each region for the year 2018.

```
world_data.loc[world_data['year'] == 2018].groupby('region').size()
```

**Comment by joelostblom** [comment]
Talking about outline, here is one.

- Learning Objectives

    - Learn how to plot with matplotlib
    - Set universal plot settings.
    - Produce scatter plots, line plots, and histograms using seaborn and matplotlib.
    - Understand how to graphically explore relationships between variables.
    - Apply grids for faceting in seaborn.
    - Use seaborn grids with matplotlib functions

- Lesson outline

    - Data visualization with matplotlib and seaborn (10 min)
        - Intro to plotting with matplotlib
        - Visualizing one quantitative variable with multiple categorical variables (50 min)
        - Visualizing the relationship of two quantitative variable with multiple categorical variables (40min)

**Pull request merged**
