### PR TITLE
4 - Update with gapminder data

### PR DESCRIPTION
**Pull request by joelostblom**
This lecture will be largely the same. The biggest change is that the intro to plotting now is in lec3. Some suggestions of what can replace this is below and it is mostly things I thought of when I developed lec2, but did not want to go off on a big tangent on.

- melt to facet by columns with seaborn. That is, melt multiple columns such as population, income etc to one variable and then used grids in seaborn to get these variables out next to each other in the grid plot.
- pd.cut to create categories of continous variables, i.e population or year intervals and use as categoricals when plotting.
- cumulative sum. sum CO2 over the years vs average CO2 of a year, all dots for many years, connect the as a time line and use size to know where the line starts, hue will be for the country. Choose top thn producers this year or something like that. also show cumulative as line plots over the years,  compare two line plots vs one timeline plot.
- add seaborn two dimensional KDE plots to the oversturateion section.
- the first plotting section has been moved to lec 3, would be cool to include 1-2 of the other plotting ideas mentioned above. The section after the plotting will stay the same I think.
- Potentially take over merge part from lec2 since it will not fit there, but not that important.

### CODE REVIEW

**Comment by joelostblom** [comment]
@SaraMati Here is a suggestion of the order. I still have to clean names and stuff and I will do that after eating. But this is all the material, just some of the varibable name and text can be improved to be smoother.

**Comment by SaraMati** [comment]
perfect. as we discussed, the new order is better. thanks. I still don't think the saturated plot makes sense for this data (or at least the variables I chose) since it's time series data. Feel free to change it with any of your suggestions above, if you agree.

**Comment by joelostblom** [comment]
Yes, I don't think it is wrong to keep that part as the diamond data set, but I will look into if there is something in gapminder that would world for the plot

**Comment by joelostblom** [comment]
@SaraMati Should be good. Ill go to bed now. We can fix last things in the morning tomorrow

**Comment by SaraMati** [comment]
Great, and yes, see you in the morning

**Pull request merged**
