### PR TITLE
2 - Update with gapminder data

### PR DESCRIPTION
**Pull request by joelostblom**
This lecture has the same flow, there is only one or two kinks to work out and I can do that when I am back. One part will be expanded and that is data cleaning. It can't be with much because everything else is the same. These are my ideas

This section will be expanded with the followingi
- use .unique (and maybe histograms) to find problems
- Splitting columns based on separator
    - can also add columns first to show that syntax

- Replace character with str.replace

   - I don’t think we will have time to cover regex or fuzzy matching, but it can be mentioned that it exists and where to read more.

- str.upper/lower, str.contains, str.strip
- na values when reading in?
- dropping and changing data types of columns

I think we will drop the merge section. We did not have time for it last workshop and we can certainly not have that AND increased cleaning.

### CODE REVIEW

**Comment by joelostblom** [comment]
@linamnt There are still a few TODOs in there, and I need to create some of the challenges, but it should be quite complete so let me know what you think and if you find any erros.

**Comment by joelostblom** [comment]
@linamnt I'm working on challenges in 1 hour!

**Comment by linamnt** [comment]
Okay I've looked it over and seems good so far! Will do a full run-through
in about an hour.

**Comment by joelostblom** [comment]
Ok I'mg oing to try to push once before then

**Comment by joelostblom** [comment]
Almost done

**Comment by joelostblom** [comment]
@linamnt Just pushed some stuff. I will keep working on challeges while you go through so just check back here before you push also. Let me know when you have read through and we can split whatever is left between us

**Comment by linamnt** [comment]
1. Adding columns challenge
2. co-erce in data cleaning does seem tangential and extra
3. I think I might not be able to cover all this the 3hrs, it took longer than expected to get through the stuff before split-apply-combine, but I think the size() section is something we can skip over if it comes down to it, I can assess how time is going at the 2hr mark and decide whether I should try to fit it in or not.

**Comment by joelostblom** [comment]
Sounds good! I will work more on this in 30 min!

**Comment by linamnt** [comment]
Am I able to push to this PR? I can't remeber how this has been done previously, if not, save some sections for me and I can take over after on my own branch once this is merged...
You've done a lot already, thanks so much!

**Comment by joelostblom** [comment]
Yes you can push to my branch and I merge? This one also allows edits from maintainers, so you might be able to edit it directly

**Comment by linamnt** [comment]
I'm actually having some trouble with GitHub since I'm not on my usual computer, but here's the challenge for the end of the cleaning data section: 

## Challenge
1. Create a new data frame called `world_data_co2` from the `world_data` data that contains only the `country`, `year`, `population` and `co2_emissions` columns and no NA values.
2. Create a new column in `clean_df_co2` called `total_co2` containing the total co2 emissions of the country using the per capita value in `co2_emissions` and the `population` column
3. Retrieve all observations that have a `total_co2` value greater than 10 000 000.

**Comment by joelostblom** [comment]
@linamnt I'm just made my last commits now then I'm done. Feel free to merge this branch or do whatever is easiest for you to continue working. Or keep sending me if you can't access from your computer. I rebased on master a few times to update column names with the dat aset.

**Comment by linamnt** [comment]
Okay sounds good, thanks Joel. I'll merge first thing in the morning after
a final look otherwise I should have my laptop to make other changes.

See you tomorrow.

**Comment by joelostblom** [comment]
@linamnt I agree with you that there is a lot here so I moved the package section to lec1. I actually had this in a PR to the old repo, but forgot to merge it.

**Pull request merged**
